# -*- coding: utf-8 -*-
"""Analisis Data UMKM V5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmFt84iv3E_hjfbU5qVZbqNCmA-lnHdE

# =============================================================================
# SISTEM PENDUKUNG KEPUTUSAN BERBASIS SPASIAL (WebGIS)
# Pemetaan & Klasterisasi UMKM - Kabupaten Bandung Barat
# Metodologi: SEMMA (Sample, Explore, Modify, Model, Assess)
# Pendekatan: Unsupervised Learning - K-Means Clustering
# Kerangka Penelitian: Design Science Research Methodology (DSRM)
# =============================================================================
# Versi   : 2.0 — Disesuaikan dengan Spesifikasi Rancangan Sistem Final
# Author  : [Nama Anda]
# Dataset : Data Agregasi BPS Level Kecamatan — Kabupaten Bandung Barat (n=16)
#
# OUTPUT YANG DIHASILKAN:
# ┌────────────────────────────────┬─────────────────────────────────────────┐
# │ File                           │ Tujuan                                  │
# ├────────────────────────────────┼─────────────────────────────────────────┤
# │ metadata_output.json           │ → INSERT tabel analisis                 │
# │                                │   (k_optimal, metrik, scaler_params,    │
# │                                │    path_grafik, dataset_snapshot)       │
# │ hasil_cluster_output.json      │ → INSERT tabel hasil_cluster            │
# │ centroid_output.json           │ → INSERT tabel centroid (nilai_fitur)   │
# │ elbow.png                      │ → path_grafik[0]                        │
# │ silhouette.png                 │ → path_grafik[1]                        │
# │ scatter_cluster.png            │ → path_grafik[2]                        │
# │ explore_heatmap_korelasi.png   │ Lampiran EDA skripsi (tidak ke path_grafik) │
# │ model_centroid_heatmap.png     │ Lampiran MODEL skripsi                  │
# │ hasil_klasterisasi_umkm_kbb.csv│ Referensi flat untuk lampiran skripsi  │
# └────────────────────────────────┴─────────────────────────────────────────┘
# =============================================================================

# ==============================================================================
# ## TAHAP 1 — SAMPLE
# Tujuan: Mengimpor library, mendefinisikan pemetaan kolom antar layer sistem,
# memuat dataset, dan memisahkan kolom identifier dari kolom fitur.
# ==============================================================================
"""

# --- 1.1 Import Library ---
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import warnings
import json
import io
from datetime import date
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score
from sklearn.decomposition import PCA
warnings.filterwarnings('ignore')
plt.rcParams['figure.dpi'] = 120
plt.rcParams['font.family'] = 'DejaVu Sans'
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False
PALETTE = ['#2563EB', '#16A34A', '#DC2626', '#D97706', '#7C3AED']
print("✅ [SAMPLE] Semua library berhasil diimpor.")
print(f"   - NumPy      v{np.__version__}")
print(f"   - Pandas     v{pd.__version__}")
print(f"   - json, datetime sudah tersedia (untuk ekspor JSON DB-ready)")

"""# --- 1.2 Pemetaan Nama Kolom Antar Layer Sistem (Konvensi) ---
# Sistem menggunakan 3 konvensi penamaan berbeda sesuai lapisan arsitektur:
#
#   LAYER             CONTOH PENAMAAN
#   ─────────────────────────────────────────────────────────────
#   DB dataset_agregat │ jml_makanan, kepadatan_penduduk, pertumbuhan
#   Script internal    │ UMKM_Makanan, Kepadatan_Penduduk, Pertumbuhan_Penduduk
#   centroid.nilai_fitur (JSON) │ f_makanan, f_kepadatan, f_pertumbuhan
#   ─────────────────────────────────────────────────────────────
#
# Ketiga mapping ini didefinisikan di sini sebagai single source of truth
# agar konsisten di seluruh script dan tidak ada KeyError saat integrasi.
"""

# Peta 1: DB column name → Script internal name
# Dipakai saat membaca input dari Laravel dataset_snapshot JSON (Opsi C)
KOLOM_MAP_DB_KE_SCRIPT = {
    'jml_makanan'       : 'UMKM_Makanan',
    'jml_kerajinan'     : 'UMKM_Kerajinan',
    'jml_fashion'       : 'UMKM_Fashion',
    'jml_jasa'          : 'UMKM_Jasa',
    'jml_lainnya'       : 'UMKM_Lainnya',
    'kepadatan_penduduk': 'Kepadatan_Penduduk',
    'pertumbuhan'       : 'Pertumbuhan_Penduduk',
    'jarak_ke_ibukota'  : 'Jarak_ke_Ibukota',
}
# Peta 2: Script internal name → JSON field name di centroid.nilai_fitur
# Dipakai saat menghasilkan centroid_output.json
KOLOM_MAP_SCRIPT_KE_JSON = {
    'UMKM_Makanan'        : 'f_makanan',
    'UMKM_Kerajinan'      : 'f_kerajinan',
    'UMKM_Fashion'        : 'f_fashion',
    'UMKM_Jasa'           : 'f_jasa',
    'UMKM_Lainnya'        : 'f_lainnya',
    'Kepadatan_Penduduk'  : 'f_kepadatan',
    'Pertumbuhan_Penduduk': 'f_pertumbuhan',
    'Jarak_ke_Ibukota'    : 'f_jarak',
}
# Peta 3: Script internal name → DB column name
# Dipakai saat menghasilkan dataset_snapshot JSON (bagian fitur)
KOLOM_MAP_SCRIPT_KE_DB = {v: k for k, v in KOLOM_MAP_DB_KE_SCRIPT.items()}
print("\n📋 [SAMPLE] Pemetaan kolom lintas layer berhasil didefinisikan.")
print(f"   Jumlah fitur yang dipetakan: {len(KOLOM_MAP_DB_KE_SCRIPT)} fitur")

"""# --- 1.3 Definisi Fitur Positif & Negatif untuk Interpretasi Berbasis Ranking ---
# Fitur POSITIF: nilai centroid tinggi → potensi ekonomi lebih baik
# Fitur NEGATIF: nilai centroid tinggi → kondisi relatif lebih lemah
# Definisi ini menjadi dasar kalkulasi skor_potensi pada TAHAP 5.
"""

FITUR_POSITIF = [
    'UMKM_Makanan', 'UMKM_Kerajinan', 'UMKM_Fashion',
    'UMKM_Jasa', 'UMKM_Lainnya',
    'Kepadatan_Penduduk', 'Pertumbuhan_Penduduk'
]
FITUR_NEGATIF = ['Jarak_ke_Ibukota']  # Jarak jauh = aksesibilitas rendah

"""
# --- 1.4 Memuat Dataset ---
# Pilih SATU opsi yang sesuai. Uncomment baris yang diperlukan."""

# ── Opsi A: Upload file CSV manual di Google Colab ──────────────────────────
from google.colab import files
uploaded = files.upload()
df_raw_load = pd.read_csv(io.BytesIO(list(uploaded.values())[0]))
# Rename kolom dari format BPS/DB ke format script:
df_raw_load = df_raw_load.rename(columns={'id_kecamatan': 'id_kecamatan'})  # sesuaikan
df_raw = df_raw_load.rename(columns=KOLOM_MAP_DB_KE_SCRIPT)

# ── Opsi B: Baca dari Google Drive ──────────────────────────────────────────
# from google.colab import drive
# drive.mount('/content/drive')
# df_raw_load = pd.read_csv('/content/drive/MyDrive/path/to/data_umkm_kbb.csv')
# df_raw = df_raw_load.rename(columns=KOLOM_MAP_DB_KE_SCRIPT)

# ── Opsi C: Dari dataset_snapshot JSON (format Laravel §4.5) ────────────────
# Format ini dihasilkan oleh Laravel Job sebelum memanggil script ini.
# Digunakan saat script dijalankan sebagai production ML service.
#
# with open('dataset_snapshot.json', 'r', encoding='utf-8') as f:
#     snapshot_raw = json.load(f)
# records = []
# for item in snapshot_raw['data']:
#     row = {
#         'id_kecamatan'  : item['id_kecamatan'],
#         'nama_kecamatan': item.get('nama_kecamatan', f"Kecamatan-{item['id_kecamatan']}"),
#     }
#     for db_col, val in item['fitur'].items():
#         script_col = KOLOM_MAP_DB_KE_SCRIPT.get(db_col, db_col)
#         row[script_col] = val
#     records.append(row)
# df_raw = pd.DataFrame(records)
# TANGGAL_SNAPSHOT = snapshot_raw.get('tanggal_snapshot', str(date.today()))
# TAHUN_DEMOGRAFI  = {item['id_kecamatan']: item.get('tahun_demografi', None)
#                     for item in snapshot_raw['data']}

# ── Opsi D: Data sintetis representatif (demonstrasi pipeline) ───────────────
# PERUBAHAN v2.0: id_kecamatan menggunakan integer 1–16 (sesuai PK INT UNSIGNED
# tabel kecamatan di MariaDB), bukan string 'KBB-001'. Ini memastikan
# hasil_cluster_output.json dapat langsung di-insert ke tabel hasil_cluster
# tanpa konversi tambahan.
np.random.seed(42)
n_kecamatan = 16
data_sintetis = {
    'id_kecamatan'        : list(range(1, n_kecamatan + 1)),          # INT sesuai DB
    'nama_kecamatan'      : [
        'Batujajar', 'Cihampelas', 'Cikalongwetan', 'Cililin', 'Cipatat',
        'Cipongkor', 'Cisarua', 'Gununghalu', 'Lembang', 'Ngamprah',
        'Padalarang', 'Parongpong', 'Rongga', 'Saguling', 'Sindangkerta',
        'Cipeundeuy'
    ],
    'UMKM_Makanan'        : np.random.randint(50, 500, n_kecamatan),
    'UMKM_Kerajinan'      : np.random.randint(10, 250, n_kecamatan),
    'UMKM_Fashion'        : np.random.randint(5,  200, n_kecamatan),
    'UMKM_Jasa'           : np.random.randint(20, 300, n_kecamatan),
    'UMKM_Lainnya'        : np.random.randint(5,  150, n_kecamatan),
    'Kepadatan_Penduduk'  : np.random.randint(200, 8000, n_kecamatan),  # jiwa/km²
    'Pertumbuhan_Penduduk': np.round(np.random.uniform(0.5, 3.5, n_kecamatan), 2),  # %
    'Jarak_ke_Ibukota'    : np.round(np.random.uniform(2.0, 55.0, n_kecamatan), 1),  # km
}
df_raw = pd.DataFrame(data_sintetis)
# Untuk Opsi D, tanggal snapshot = hari ini, tahun demografi = None (sintetis)
TANGGAL_SNAPSHOT = str(date.today())
TAHUN_DEMOGRAFI  = {i: None for i in range(1, n_kecamatan + 1)}
print(f"\n✅ [SAMPLE] Dataset berhasil dimuat. Shape: {df_raw.shape}")
print(f"   Tipe id_kecamatan: {df_raw['id_kecamatan'].dtype} (harus int)")

"""
# --- 1.5 Definisi Kolom Identifier dan Fitur ---
# Identifier TIDAK PERNAH dimasukkan ke dalam proses training."""

COLS_IDENTIFIER = ['id_kecamatan', 'nama_kecamatan']
# Semua 8 fitur mentah (untuk eksplorasi & imputasi)
COLS_FITUR = [
    'UMKM_Makanan', 'UMKM_Kerajinan', 'UMKM_Fashion',
    'UMKM_Jasa', 'UMKM_Lainnya',
    'Kepadatan_Penduduk', 'Pertumbuhan_Penduduk', 'Jarak_ke_Ibukota',
]
# 5 kolom UMKM (nilai absolut)
COLS_UMKM_5 = ['UMKM_Makanan', 'UMKM_Kerajinan', 'UMKM_Fashion', 'UMKM_Jasa', 'UMKM_Lainnya']
# 4 sektor utama yang dibandingkan (Lainnya selalu bottom-2, tidak masuk ranking utama)
COLS_UMKM_4_MAIN = ['UMKM_Makanan', 'UMKM_Kerajinan', 'UMKM_Fashion', 'UMKM_Jasa']
# 5 kolom PROPORSI — dihasilkan di MODIFY 3.2, dipakai untuk clustering (Opsi B)
# Proporsi = share (%) setiap sektor terhadap total UMKM kecamatan itu
COLS_PROP = ['PROP_Makanan', 'PROP_Kerajinan', 'PROP_Fashion', 'PROP_Jasa', 'PROP_Lainnya']
# Fitur demografis & spasial — tetap absolut (tidak diubah ke proporsi)
COLS_DEMOGRAFI = ['Kepadatan_Penduduk', 'Pertumbuhan_Penduduk', 'Jarak_ke_Ibukota']
# Fitur gabungan untuk K-Means: 5 proporsi sektor + 3 demografis = 8 fitur
# Dengan proporsi, kecamatan yang Fashion-dominant akan benar-benar berbeda
# dari yang Makanan-dominant, terlepas dari besar kecilnya nilai absolut.
COLS_FITUR_CLUSTER = COLS_PROP + COLS_DEMOGRAFI
print(f"\n📋 [SAMPLE] Definisi Kolom:")
print(f"   Identifier (Tidak di-training)  : {COLS_IDENTIFIER}")
print(f"   Fitur mentah (8, untuk eksplorasi) : {COLS_FITUR}")
print(f"   Fitur clustering (8)            : {COLS_FITUR_CLUSTER}")
print(f"     └─ 5 proporsi sektor (%) + 3 demografis/spasial")
print(f"\n{'='*70}")
print(df_raw.head())

"""# ==============================================================================
# ## TAHAP 2 — EXPLORE
# Tujuan: Memahami karakteristik data mentah sebelum transformasi apapun.
# Sesuai metodologi SEMMA, eksplorasi difokuskan pada statistik agregat,
# pemeriksaan integritas data, dan analisis korelasi antar fitur.
#
# Visualisasi per-variabel (histogram/boxplot) DIHINDARI: dengan n=16,
# estimasi distribusi sangat tidak stabil dan dapat menyesatkan.
# Ini juga merupakan keterbatasan penelitian yang dicatat dalam §3.3 spesifikasi.
# ==============================================================================

# --- 2.1 Informasi Tipe Data dan Struktur DataFrame ---
"""

print("\n📌 [EXPLORE 2.1] Informasi Tipe Data (df.info()):\n")
df_raw.info()

"""# --- 2.2 Cuplikan Data (head) ---

"""

print("\n📌 [EXPLORE 2.2] Lima baris pertama dataset (df.head()):\n")
print(df_raw.head().to_string(index=False))

"""# --- 2.3 Statistik Deskriptif + Coefficient of Variation ---

"""

print("\n📌 [EXPLORE 2.3] Statistik Deskriptif Fitur:\n")
desc = df_raw[COLS_FITUR].describe().T
desc['range'] = desc['max'] - desc['min']
desc['cv_%']  = (desc['std'] / desc['mean'] * 100).round(2)   # Koefisien Variasi
print(desc.round(2).to_string())
print("\n  Interpretasi CV% (Koefisien Variasi):")
print("  - CV% tinggi antar fitur mengkonfirmasi perbedaan skala ekstrem.")
print("  - Ini menjustifikasi penggunaan StandardScaler di tahap MODIFY.")

"""# --- 2.4 Pemeriksaan Missing Values ---

"""

print("\n📌 [EXPLORE 2.4] Pemeriksaan Missing Values per Fitur:\n")
missing = df_raw[COLS_FITUR].isnull().sum().reset_index()
missing.columns = ['Fitur', 'Jumlah_Missing']
missing['Persentase (%)'] = (missing['Jumlah_Missing'] / len(df_raw) * 100).round(2)
print(missing.to_string(index=False))
total_missing = missing['Jumlah_Missing'].sum()
if total_missing == 0:
    print("\n  ✅ Tidak ada missing values terdeteksi.")
else:
    print(f"\n  ⚠️  Total {total_missing} missing values ditemukan.")
    print(f"     Seluruhnya akan ditangani via Median Imputation di tahap MODIFY.")
    print(f"     Sesuai §3.1 spesifikasi: data tidak dihapus, tetap n=16.")

"""# --- 2.5 Heatmap Korelasi Pearson ---

"""

print("\n📌 [EXPLORE 2.5] Membuat Heatmap Korelasi Pearson...\n")
corr_matrix = df_raw[COLS_FITUR].corr(method='pearson')
fig, ax = plt.subplots(figsize=(10, 8))
sns.heatmap(
    corr_matrix,
    annot=True, fmt='.2f',
    cmap='RdYlGn', center=0,
    vmin=-1, vmax=1,
    linewidths=0.5, linecolor='white',
    ax=ax, annot_kws={'size': 9},
    square=True
)
ax.set_title(
    'Heatmap Korelasi Pearson Antar Fitur UMKM\nKabupaten Bandung Barat (Data BPS)',
    fontsize=13, fontweight='bold', pad=15
)
ax.tick_params(axis='x', rotation=45, labelsize=9)
ax.tick_params(axis='y', rotation=0, labelsize=9)
plt.tight_layout()
plt.savefig('explore_heatmap_korelasi.png', bbox_inches='tight')
plt.show()
print("  ✅ Disimpan: explore_heatmap_korelasi.png (lampiran EDA skripsi)")
print("  Interpretasi: Hijau (+1) = korelasi positif | Merah (-1) = korelasi negatif")

"""# ==============================================================================
# ## TAHAP 3 — MODIFY
# Tujuan: Persiapan data agar siap dikonsumsi algoritma K-Means.
# Dua transformasi dilakukan berurutan:
# (1) Median Imputation — menangani missing values tanpa mendistorsi distribusi.
# (2) StandardScaler (Z-score) — menyetarakan skala semua fitur agar tidak ada
#     fitur yang mendominasi perhitungan jarak Euclidean.
# Parameter StandardScaler (mean_ dan scale_) DISIMPAN sebagai JSON karena
# dibutuhkan oleh sistem untuk mengassign cluster pada data baru tanpa re-fit
# (sesuai kolom analisis.scaler_params di spesifikasi §6.6).
# ==============================================================================

# --- 3.1 Imputasi Missing Values dengan Median ---
"""

print("\n📌 [MODIFY 3.1] Imputasi Missing Values dengan Median...")
print("   Justifikasi: Median lebih robust terhadap outlier dibanding Mean.")
print("   Dengan n=16, satu nilai ekstrem dapat sangat menggeser Mean.\n")
df_processed = df_raw.copy()
# ── FLAG PENTING: Kecamatan dengan banyak NA ────────────────────────────────
# Kecamatan yang memiliki banyak kolom UMKM bernilai NA akan mendapat nilai
# imputasi median untuk SEMUA fitur UMKM-nya. Ini dapat menyebabkan
# 'imputation bias': kecamatan tersebut terlihat memiliki profil UMKM rata-rata
# padahal sebenarnya tidak ada data yang valid.
# Catatan ini penting untuk narasi keterbatasan penelitian di Bab IV skripsi.
COLS_UMKM = ['UMKM_Makanan', 'UMKM_Kerajinan', 'UMKM_Fashion', 'UMKM_Jasa', 'UMKM_Lainnya']
df_raw['n_umkm_na'] = df_raw[COLS_UMKM].isnull().sum(axis=1)
kec_banyak_na = df_raw[df_raw['n_umkm_na'] >= 3][['nama_kecamatan', 'n_umkm_na']]
if len(kec_banyak_na) > 0:
    print("  ⚠️  PERINGATAN — Kecamatan dengan ≥3 kolom UMKM bernilai NA:")
    print(kec_banyak_na.to_string(index=False))
    print("  Interpretasi cluster kecamatan ini PERLU DIVALIDASI secara kualitatif")
    print("  karena nilainya sebagian besar berasal dari imputasi, bukan data riil.")
    # Simpan daftar untuk digunakan pada ASSESS
    KEG_IMPUTASI_TINGGI = kec_banyak_na['nama_kecamatan'].tolist()
else:
    KEG_IMPUTASI_TINGGI = []
    print("  ✅ Tidak ada kecamatan dengan banyak NA pada kolom UMKM.")
df_processed = df_raw.drop(columns=['n_umkm_na'], errors='ignore').copy()
log_imputasi = []
for col in COLS_FITUR:
    n_missing = df_processed[col].isnull().sum()
    if n_missing > 0:
        median_val = df_processed[col].median()
        df_processed[col] = df_processed[col].fillna(median_val)
        log_imputasi.append({
            'Fitur'        : col,
            'Missing Diisi': n_missing,
            'Nilai Median' : round(median_val, 4)
        })
if log_imputasi:
    print()
    print(pd.DataFrame(log_imputasi).to_string(index=False))
    print(f"\n  ✅ {len(log_imputasi)} fitur berhasil diimputasi.")
else:
    print("  ✅ Tidak ada imputasi diperlukan (dataset sudah bersih).")
# Verifikasi tidak ada missing tersisa
assert df_processed[COLS_FITUR].isnull().sum().sum() == 0, "❌ ERROR: Masih ada missing values!"
print("  ✅ Verifikasi: 0 missing values tersisa.")

"""# --- 3.2 BARU v3.0: Kalkulasi Proporsi Sektor UMKM (Opsi B) ---
# MENGAPA PROPORSI BUKAN ABSOLUT:
# Jika menggunakan nilai absolut, kecamatan dengan banyak UMKM akan selalu
# mendominasi semua sektor sekaligus, sehingga kedua cluster memiliki profil
# centroid yang mirip (Makanan tertinggi, Lainnya terendah di semua cluster).
#
# Dengan PROPORSI (share %): kecamatan yang 60% UMKM-nya adalah Fashion akan
# benar-benar berbeda dari kecamatan yang 60% UMKM-nya adalah Makanan,
# meskipun jumlah absolutnya berbeda jauh. Ini langsung menjawab tujuan:
# "klaster mana yang didominasi sektor apa?"
#
# Formula: prop_sektor = umkm_sektor / total_umkm_5_sektor
# Kecamatan dengan total=0 (semua NA diimputasi ke 0): diberi 0.2 uniform (20%)
"""

print("\n📌 [MODIFY 3.2] Kalkulasi Proporsi Sektor UMKM (v3.0 — Opsi B)...")
print("   Formula: PROP_Sektor = UMKM_Sektor / Total_UMKM (5 sektor)\n")
df_processed['total_umkm_5'] = df_processed[COLS_UMKM_5].sum(axis=1)
for col_umkm, col_prop in zip(COLS_UMKM_5, COLS_PROP):
    # Bagi dengan total; jika total = 0 (kecamatan tanpa data), beri proporsi uniform 1/5
    df_processed[col_prop] = np.where(
        df_processed['total_umkm_5'] > 0,
        df_processed[col_umkm] / df_processed['total_umkm_5'],
        0.2  # uniform 20% jika tidak ada data sama sekali
    )
# Verifikasi: tiap baris harus sum ≈ 1.0
sum_prop = df_processed[COLS_PROP].sum(axis=1)
assert (sum_prop.round(6) == 1.0).all(), "❌ ERROR: Proporsi tidak menjumlah ke 1!"
print("   Tabel proporsi sektor per kecamatan (%, 2 desimal):")
prop_display = df_processed[['nama_kecamatan']].copy()
prop_display[COLS_PROP] = (df_processed[COLS_PROP] * 100).round(2)
prop_display.columns = ['Kecamatan'] + [c.replace('PROP_', '') for c in COLS_PROP]
print(prop_display.to_string(index=False))
print(f"\n  ✅ Proporsi berhasil dihitung. Tiap baris sum = 1.0 (100%)")
print(f"  ✅ Kecamatan dengan semua NA → proporsi 20% seragam (sudah di-flag sebelumnya)")

"""# --- 3.3 Standardisasi Z-score (StandardScaler) pada COLS_FITUR_CLUSTER ---
# StandardScaler diterapkan pada 8 fitur clustering:
# 5 proporsi sektor (sudah range 0-1) + 3 demografis (range berbeda-beda).
# Scaling tetap diperlukan karena Kepadatan_Penduduk (ratusan-ribuan) vs
# proporsi (0.0-1.0) memiliki skala sangat berbeda.
"""

print("\n📌 [MODIFY 3.3] Standardisasi Z-score pada Fitur Clustering...")
print("   Fitur yang di-scale: 5 proporsi UMKM + 3 demografis/spasial")
print("   Formula: z = (x - μ) / σ  →  Hasil: mean≈0, std≈1 per fitur\n")
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_processed[COLS_FITUR_CLUSTER])
df_scaled = pd.DataFrame(X_scaled, columns=COLS_FITUR_CLUSTER)
print("   Verifikasi hasil (mean dan std setelah transformasi):")
verif = pd.DataFrame({
    'Fitur'          : COLS_FITUR_CLUSTER,
    'Mean (setelah)' : df_scaled.mean().round(10).values,
    'Std  (setelah)' : df_scaled.std().round(4).values,
    'Min  (setelah)' : df_scaled.min().round(4).values,
    'Max  (setelah)' : df_scaled.max().round(4).values,
})
print(verif.to_string(index=False))
print("\n  ✅ Semua fitur clustering kini berada pada skala setara (Z-score).")

"""# --- 3.4 Ekspor scaler_params → untuk kolom analisis.scaler_params ---
# Parameter ini wajib disimpan agar cluster assignment data baru di production
# menggunakan normalisasi yang SAMA. Catatan: karena clustering kini berbasis
# proporsi, Laravel perlu hitung proporsi dulu SEBELUM mengirim ke Python.
"""

print("\n📌 [MODIFY 3.4] Mengekspor scaler_params...")
scaler_params_dict = {
    "feature_names" : COLS_FITUR_CLUSTER,
    "mean_"         : scaler.mean_.tolist(),
    "scale_"        : scaler.scale_.tolist(),
    # Penanda unit eksplisit: f_prop_* di centroid.nilai_fitur berskala persen (0–100),
    # BUKAN fraksi (0–1). Pastikan parser sistem lain membaca catatan ini.
    "catatan_unit"  : "f_prop_* dalam skala persen (0-100)",
    "catatan"       : "Fitur input adalah PROPORSI (0-1), bukan nilai absolut.",
}
for i, col in enumerate(COLS_FITUR_CLUSTER):
    print(f"   {col:<25} mean_={scaler_params_dict['mean_'][i]:8.4f}  "
          f"scale_={scaler_params_dict['scale_'][i]:8.4f}")
print("\n  ✅ scaler_params siap.")

"""# ==============================================================================
# ## TAHAP 4 — MODEL
# Tujuan: Menentukan K optimal dan membangun model K-Means final.
#
# Dua metode komplementer digunakan untuk memilih K:
# (1) Elbow Method — mencari "titik siku" pada kurva WCSS (Inertia).
#     Disimpan sebagai file TERPISAH: elbow.png (→ path_grafik[0])
# (2) Silhouette Score — memilih K dengan skor tertinggi.
#     Disimpan sebagai file TERPISAH: silhouette.png (→ path_grafik[1])
#
# PERUBAHAN v2.0: Elbow dan Silhouette kini disimpan sebagai 2 file PNG
# terpisah, sesuai spec §3.6 dan §6.6 (path_grafik berisi array 3 URL).
# ==============================================================================

# --- 4.1 Pencarian K Optimal (K=2 hingga K=8) ---
"""

print("\n📌 [MODEL 4.1] Pencarian K Optimal (K=2 hingga K=8)...\n")
K_RANGE    = range(2, 9)
inertia    = []
sil_scores = []
for k in K_RANGE:
    km = KMeans(n_clusters=k, init='k-means++', n_init=20, random_state=42)
    km.fit(X_scaled)
    inertia.append(km.inertia_)
    sil_scores.append(silhouette_score(X_scaled, km.labels_))
    print(f"   K={k} | Inertia: {km.inertia_:8.2f} | Silhouette Score: "
          f"{silhouette_score(X_scaled, km.labels_):.4f}")
# Tentukan K optimal dari Silhouette Score tertinggi
best_k_idx = sil_scores.index(max(sil_scores))
K_OPTIMAL  = list(K_RANGE)[best_k_idx]
print(f"\n  ✅ K Optimal terpilih: K = {K_OPTIMAL}")
print(f"     Justifikasi: K={K_OPTIMAL} menghasilkan Silhouette Score tertinggi "
      f"({max(sil_scores):.4f})")

"""# --- 4.2 Plot Elbow Method — disimpan sebagai elbow.png (path_grafik[0]) ---
# PERUBAHAN v2.0: File terpisah dari silhouette.png sesuai spec §6.6
"""

print("\n📌 [MODEL 4.2] Membuat plot Elbow Method → elbow.png...")
fig, ax = plt.subplots(figsize=(8, 5))
ax.plot(
    K_RANGE, inertia, 'o-',
    color='#2563EB', linewidth=2.5, markersize=9,
    markerfacecolor='white', markeredgewidth=2.5
)
# Tandai titik K optimal
ax.plot(K_OPTIMAL, inertia[best_k_idx], 'o',
        color='#DC2626', markersize=14, zorder=5, label=f'K Optimal = {K_OPTIMAL}')
ax.set_xlabel('Jumlah Klaster (K)', fontsize=11)
ax.set_ylabel('Inertia / WCSS\n(Within-Cluster Sum of Squares)', fontsize=11)
ax.set_title(
    'Elbow Method — Penentuan K Optimal\n'
    'K-Means Clustering UMKM Kabupaten Bandung Barat',
    fontsize=12, fontweight='bold', pad=12
)
ax.xaxis.set_major_locator(ticker.MultipleLocator(1))
ax.grid(axis='y', linestyle='--', alpha=0.5)
ax.legend(fontsize=10)
for x, y in zip(K_RANGE, inertia):
    ax.annotate(f'{y:.1f}', (x, y),
                textcoords='offset points', xytext=(0, 12),
                ha='center', fontsize=8, color='#374151')
plt.tight_layout()
plt.savefig('elbow.png', bbox_inches='tight')
plt.show()
print("  ✅ Disimpan: elbow.png → path_grafik[0]")

"""# --- 4.3 Plot Silhouette Score per K — disimpan sebagai silhouette.png (path_grafik[1]) ---
# PERUBAHAN v2.0: File terpisah dari elbow.png sesuai spec §6.6
"""

print("\n📌 [MODEL 4.3] Membuat plot Silhouette Score → silhouette.png...")
fig, ax = plt.subplots(figsize=(8, 5))
colors = [PALETTE[i % len(PALETTE)] for i in range(len(K_RANGE))]
bars   = ax.bar(K_RANGE, sil_scores, color=colors, edgecolor='white',
                linewidth=0.8, alpha=0.88)
# Tebalkan border pada K optimal
bars[best_k_idx].set_edgecolor('#1D1D1D')
bars[best_k_idx].set_linewidth(2.5)
ax.set_xlabel('Jumlah Klaster (K)', fontsize=11)
ax.set_ylabel('Silhouette Score', fontsize=11)
ax.set_title(
    'Silhouette Score per Nilai K\n'
    'K-Means Clustering UMKM Kabupaten Bandung Barat',
    fontsize=12, fontweight='bold', pad=12
)
ax.xaxis.set_major_locator(ticker.MultipleLocator(1))
ax.set_ylim(0, max(sil_scores) * 1.3)
ax.grid(axis='y', linestyle='--', alpha=0.5)
for bar, score in zip(bars, sil_scores):
    ax.text(bar.get_x() + bar.get_width() / 2., bar.get_height() + 0.005,
            f'{score:.3f}', ha='center', va='bottom',
            fontsize=9, fontweight='bold')
# Anotasi K optimal
ax.annotate(
    f'  ← K Optimal = {K_OPTIMAL}\n     (Skor Tertinggi)',
    xy=(K_OPTIMAL, sil_scores[best_k_idx]),
    xytext=(K_OPTIMAL + 0.5, sil_scores[best_k_idx] * 1.0),
    fontsize=9, color='#DC2626',
    arrowprops=dict(arrowstyle='->', color='#DC2626', lw=1.5)
)
plt.tight_layout()
plt.savefig('silhouette.png', bbox_inches='tight')
plt.show()
print("  ✅ Disimpan: silhouette.png → path_grafik[1]")

"""# --- 4.4 Fitting Model K-Means Final ---

"""

print(f"\n📌 [MODEL 4.4] Fitting K-Means Final (K={K_OPTIMAL})...")
print(f"   - init='k-means++'  : inisialisasi cerdas, menghindari local optimum")
print(f"   - n_init=50          : 50 restart, ambil hasil dengan inertia terkecil")
print(f"   - max_iter=500       : batas iterasi per run")
print(f"   - random_state=42    : reproducibility hasil\n")
kmeans_final = KMeans(
    n_clusters=K_OPTIMAL,
    init='k-means++',
    n_init=50,
    max_iter=500,
    random_state=42
)
kmeans_final.fit(X_scaled)
print(f"  ✅ Model K-Means final berhasil di-fit.")
print(f"   Inertia final  : {kmeans_final.inertia_:.4f}")
print(f"   Konvergensi    : {kmeans_final.n_iter_} iterasi")

"""# --- 4.5 Heatmap Profil Centroid (Skala Terstandarisasi) ---

"""

print("\n📌 [MODEL 4.5] Visualisasi Profil Centroid Klaster...")
centroid_scaled_df = pd.DataFrame(
    kmeans_final.cluster_centers_,
    columns=COLS_FITUR,
    index=[f'Klaster {i}' for i in range(K_OPTIMAL)]
)
# Tampilkan centroid skala asli
centroids_asli_df = pd.DataFrame(
    scaler.inverse_transform(kmeans_final.cluster_centers_),
    columns=COLS_FITUR,
    index=[f'Klaster {i}' for i in range(K_OPTIMAL)]
)
print("\n  Nilai Centroid (Skala Asli — untuk interpretasi):")
print(centroids_asli_df.round(2).to_string())
fig, ax = plt.subplots(figsize=(12, max(4, K_OPTIMAL * 1.2)))
sns.heatmap(
    centroid_scaled_df,
    annot=True, fmt='.2f',
    cmap='coolwarm', center=0,
    linewidths=0.5, linecolor='white',
    ax=ax, annot_kws={'size': 9}
)
ax.set_title(
    f'Profil Centroid Klaster (Nilai Z-score, K={K_OPTIMAL})\n'
    f'Merah = Di Atas Rata-rata | Biru = Di Bawah Rata-rata',
    fontsize=12, fontweight='bold', pad=12
)
ax.tick_params(axis='x', rotation=40, labelsize=9)
ax.tick_params(axis='y', rotation=0, labelsize=9)
plt.tight_layout()
plt.savefig('model_centroid_heatmap.png', bbox_inches='tight')
plt.show()
print("  ✅ Disimpan: model_centroid_heatmap.png (lampiran MODEL skripsi)")

"""# ==============================================================================
# ## TAHAP 5 — ASSESS
# Tujuan: Evaluasi objektif kualitas model dan ekspor seluruh output yang
# dibutuhkan sistem Laravel + MariaDB dalam format JSON yang siap di-insert.
#
# Evaluasi menggunakan metrik Unsupervised Learning:
# (1) Silhouette Coefficient — kohesi intra-klaster dan separasi inter-klaster
# (2) Davies-Bouldin Index   — kemiripan rata-rata antar klaster (semakin kecil=baik)
#
# PENTING: Confusion Matrix, Accuracy, Precision, F1 adalah metrik Supervised
# Learning dan TIDAK DAPAT digunakan di sini (tidak ada ground truth label).
#
# OUTPUT BARU v2.0:
# (A) Interpretasi cluster berbasis ranking skor_potensi centroid (algoritmik)
# (B) scatter_cluster.png — scatter PCA 2D (path_grafik[2])
# (C) hasil_cluster_output.json — siap INSERT ke tabel hasil_cluster
# (D) centroid_output.json      — siap INSERT ke tabel centroid
# (E) metadata_output.json      — siap INSERT ke tabel analisis
# ==============================================================================
"""

# Ambil label klaster dari model final
# (Didefinisikan di sini agar cell ini bisa dijalankan secara mandiri)
labels = kmeans_final.labels_

"""# --- 5.1 Kalkulasi Metrik Evaluasi ---

"""

print("\n📌 [ASSESS 5.1] Kalkulasi Metrik Evaluasi Klasterisasi...\n")
silhouette_final = silhouette_score(X_scaled, labels)
dbi_final        = davies_bouldin_score(X_scaled, labels)
print(f"   {'Metrik':<35} {'Nilai':>10}   Interpretasi")
print(f"   {'-'*70}")
print(f"   {'Silhouette Coefficient':<35} {silhouette_final:>10.4f}   ", end='')
if   silhouette_final > 0.70: print("Struktur klaster KUAT ✅")
elif silhouette_final > 0.50: print("Struktur klaster CUKUP BAIK ✅")
elif silhouette_final > 0.25: print("Struktur klaster LEMAH ⚠️")
else:                         print("Struktur klaster TIDAK SIGNIFIKAN ❌")
print(f"   {'Davies-Bouldin Index':<35} {dbi_final:>10.4f}   ", end='')
if   dbi_final < 0.50: print("Separasi klaster SANGAT BAIK ✅")
elif dbi_final < 1.00: print("Separasi klaster BAIK ✅")
elif dbi_final < 1.50: print("Separasi klaster CUKUP ⚠️")
else:                  print("Separasi klaster BURUK ❌")
print(f"\n   Catatan §3.3 Spesifikasi (Keterbatasan Penelitian):")
print(f"   n=16 menyebabkan nilai metrik kurang stabil dibanding dataset besar.")
print(f"   Validasi tambahan dilakukan via profil centroid vs. data BPS riil.")

"""# --- 5.2 Interpretasi Cluster Berbasis Profil Sektor UMKM (v3.0) ---
#
# TUJUAN ANALISIS YANG BENAR:
# Mengetahui 2-3 sektor UMKM yang paling tinggi dan paling rendah dari
# setiap klaster kecamatan. Bukan menilai tingkat kemakmuran/potensi,
# melainkan mengidentifikasi PROFIL DOMINANSI SEKTOR yang membedakan
# setiap kelompok kecamatan.
#
# Contoh output yang diharapkan:
#   Klaster 0: "Dominan Fashion & Jasa | Rendah Kerajinan"
#   Klaster 1: "Dominan Makanan & Kerajinan | Rendah Fashion"
#
# MEKANISME (objektif, berbasis centroid skala asli):
#   1. Ambil nilai centroid tiap sektor UMKM (skala asli, bukan Z-score)
#   2. Hitung share (%) tiap sektor terhadap total UMKM per klaster
#   3. Urutkan sektor dari tertinggi ke terendah
#   4. Label = Top-2 tertinggi + Bottom-1 terendah
#   5. Bandingkan antar klaster: sektor mana yang di atas rata-rata lintas klaster?
#
# Catatan: Fitur demografis & spasial tetap digunakan dalam clustering
# (memberikan konteks wilayah), tetapi penamaan klaster murni berbasis
# profil sektor UMKM sesuai tujuan penelitian.

"""

print("\n📌 [ASSESS 5.2] Interpretasi Cluster Berbasis Profil Sektor UMKM (v3.0)...")
print("   Tujuan: Mengidentifikasi 2-3 sektor UMKM dominan & rendah per klaster\n")
# Nama singkat sektor untuk label dan visualisasi
COLS_UMKM_FITUR = [
    'UMKM_Makanan', 'UMKM_Kerajinan', 'UMKM_Fashion',
    'UMKM_Jasa', 'UMKM_Lainnya'
]
NAMA_SEKTOR = {
    'UMKM_Makanan'  : 'Makanan',
    'UMKM_Kerajinan': 'Kerajinan',
    'UMKM_Fashion'  : 'Fashion',
    'UMKM_Jasa'     : 'Jasa',
    'UMKM_Lainnya'  : 'Lainnya',
}
# --- Hitung rata-rata lintas klaster per sektor (sebagai baseline pembanding) ---
centroid_asli_eval = centroids_asli_df.copy()
rata_rata_lintas_klaster = centroid_asli_eval[COLS_UMKM_FITUR].mean(axis=0)
print("   Rata-rata nilai centroid per sektor (baseline lintas klaster):")
for col, val in rata_rata_lintas_klaster.items():
    print(f"     {NAMA_SEKTOR[col]:<12}: {val:>8.1f} unit")
# --- Profil tiap klaster: ranking sektor + share + perbandingan vs baseline ---
CLUSTER_KE_INTERPRETASI = {}
CLUSTER_KE_PROFIL_DETAIL = {}
print(f"\n{'='*65}")
print(f"   PROFIL SEKTOR PER KLASTER (K={K_OPTIMAL})")
print(f"{'='*65}")
for cluster_id in range(K_OPTIMAL):
    centroid_umkm = centroid_asli_eval.loc[f'Klaster {cluster_id}', COLS_UMKM_FITUR]
    total_umkm    = centroid_umkm.sum()
    # Hitung share (%) tiap sektor terhadap total UMKM klaster
    share_persen  = (centroid_umkm / total_umkm * 100) if total_umkm > 0 else centroid_umkm * 0
    # Tandai sektor di atas / di bawah baseline lintas klaster
    di_atas_baseline = centroid_umkm > rata_rata_lintas_klaster
    # Urutkan sektor: dari nilai centroid tertinggi ke terendah
    ranking_sektor = centroid_umkm.sort_values(ascending=False)
    # Ambil top-2 (tertinggi) dan bottom-1 (terendah)
    top_2    = [NAMA_SEKTOR[s] for s in ranking_sektor.index[:2]]
    bottom_1 = NAMA_SEKTOR[ranking_sektor.index[-1]]
    # Label interpretasi: deskriptif berbasis sektor
    label = f"Dominan {' & '.join(top_2)} | Rendah {bottom_1}"
    CLUSTER_KE_INTERPRETASI[cluster_id] = label
    # Simpan profil detail untuk ekspor JSON
    CLUSTER_KE_PROFIL_DETAIL[cluster_id] = {
        "label_cluster"   : cluster_id,
        "interpretasi"    : label,
        "total_umkm"      : round(float(total_umkm), 1),
        "sektor_dominan"  : top_2,
        "sektor_rendah"   : [bottom_1],
        "ranking_sektor"  : [
            {
                "sektor"    : NAMA_SEKTOR[s],
                "nilai"     : round(float(centroid_umkm[s]), 1),
                "share_pct" : round(float(share_persen[s]), 1),
                "vs_baseline": "ATAS" if di_atas_baseline[s] else "BAWAH"
            }
            for s in ranking_sektor.index
        ]
    }
    # Tampilkan ringkasan klaster
    print(f"\n  📍 Klaster {cluster_id}: {label}")
    print(f"     Total UMKM centroid: {total_umkm:.0f} unit")
    print(f"     {'Sektor':<12} {'Nilai':>8} {'Share':>7}  {'vs Baseline':>12}")
    print(f"     {'-'*42}")
    for i, sektor in enumerate(ranking_sektor.index):
        nilai  = centroid_umkm[sektor]
        share  = share_persen[sektor]
        status = "↑ di atas" if di_atas_baseline[sektor] else "↓ di bawah"
        marker = " ◀ DOMINAN" if i < 2 else (" ◀ RENDAH" if i == len(ranking_sektor) - 1 else "")
        print(f"     {NAMA_SEKTOR[sektor]:<12} {nilai:>8.1f} {share:>6.1f}%  {status:>12}{marker}")
print(f"\n{'='*65}")
# --- Tabel perbandingan antar klaster untuk semua sektor ---
print(f"\n   Tabel Komparasi Nilai Centroid Sektor Antar Klaster (Skala Asli):")
print(f"   (Berguna untuk narasi Bab IV — sektor mana yang membedakan klaster)\n")
tabel_komparasi = centroid_asli_eval[COLS_UMKM_FITUR].copy()
tabel_komparasi.columns = [NAMA_SEKTOR[c] for c in tabel_komparasi.columns]
tabel_komparasi['Total_UMKM'] = tabel_komparasi.sum(axis=1)
print(tabel_komparasi.round(1).to_string())
# Identifikasi sektor yang menjadi PEMBEDA UTAMA antar klaster
std_per_sektor = centroid_asli_eval[COLS_UMKM_FITUR].std(axis=0)
print(f"\n   Sektor dengan variasi terbesar antar klaster")
print(f"   (standar deviasi nilai centroid — semakin besar = makin membedakan):")
std_sorted = std_per_sektor.sort_values(ascending=False)
for col, std_val in std_sorted.items():
    bar = "█" * int(std_val / std_sorted.max() * 20)
    print(f"     {NAMA_SEKTOR[col]:<12}: {std_val:>8.2f}  {bar}")
# --- Tempelkan label cluster ke dataframe ---
df_hasil = df_raw.copy()
df_hasil['label_cluster'] = labels
df_hasil['interpretasi']  = df_hasil['label_cluster'].map(CLUSTER_KE_INTERPRETASI)
# Tambahkan flag kecamatan dengan imputasi tinggi
# Nilai ENUM di DB: 'OK' | 'PERLU_VALIDASI' (underscore wajib, bukan spasi)
df_hasil['flag_imputasi'] = df_hasil['nama_kecamatan'].apply(
    lambda x: 'PERLU_VALIDASI' if x in KEG_IMPUTASI_TINGGI else 'OK'
)
# Simpan ke centroid_eval_df untuk kompatibilitas bagian ekspor
centroid_eval_df = centroid_scaled_df.copy()
centroid_eval_df['skor_potensi'] = 0.0   # placeholder — tidak digunakan di v3.0
centroid_eval_df['rank_potensi'] = 0     # placeholder — tidak digunakan di v3.0
if KEG_IMPUTASI_TINGGI:
    print(f"\n   ⚠️  Kecamatan berikut perlu validasi kualitatif (data UMKM sebagian besar diimputasi):")
    flagged = df_hasil[df_hasil['flag_imputasi'] == 'PERLU_VALIDASI']
    for _, row in flagged.iterrows():
        print(f"       - {row['nama_kecamatan']}: Cluster {row['label_cluster']} "
              f"({row['interpretasi']}) ← sebagian besar nilai UMKM diimputasi")

"""# --- 5.3 Distribusi Anggota per Klaster ---

"""

print("\n📌 [ASSESS 5.3] Distribusi Anggota per Klaster:\n")
dist = df_hasil.groupby(['label_cluster', 'interpretasi']).agg(
    Jumlah_Kecamatan=('nama_kecamatan', 'count'),
    Anggota=('nama_kecamatan', lambda x: ', '.join(x))
).reset_index()
print(dist.to_string(index=False))

"""# --- 5.4 BARU v3.0: Ranking Sektor Per Kecamatan (Opsi A) ---
# Tujuan utama analisis: mengetahui 2 sektor UMKM tertinggi dan 2 terendah
# dari SETIAP KECAMATAN secara individual — bukan dari centroid klaster.
#
# Aturan berdasarkan spesifikasi pengguna:
#   - Top-2 : 2 sektor dengan nilai absolut tertinggi dari {Makanan, Kerajinan, Fashion, Jasa}
#   - Bottom-2:
#       [1] Sektor terendah dari {Makanan, Kerajinan, Fashion, Jasa}
#       [2] Lainnya (selalu masuk bottom-2 karena secara empiris selalu terendah)
#
# Catatan: ranking berbasis nilai ABSOLUT dari data kecamatan itu sendiri
# (bukan centroid, bukan proporsi) sehingga mencerminkan kondisi riil.
"""

print("\n📌 [ASSESS 5.4] Ranking Sektor Per Kecamatan (v3.0 — Opsi A)...")
print("   Ranking berbasis nilai ABSOLUT data kecamatan (bukan centroid klaster)\n")
NAMA_SEKTOR_PENDEK = {
    'UMKM_Makanan'  : 'Makanan',
    'UMKM_Kerajinan': 'Kerajinan',
    'UMKM_Fashion'  : 'Fashion',
    'UMKM_Jasa'     : 'Jasa',
    'UMKM_Lainnya'  : 'Lainnya',
}
# Hitung per kecamatan
sektor_top1_list     = []
sektor_top2_list     = []
sektor_bottom1_list  = []
sektor_bottom2_list  = []   # selalu Lainnya
ranking_detail_list  = []
for idx, row in df_processed.iterrows():
    # Nilai absolut 4 sektor utama (setelah imputasi)
    nilai_4 = {col: row[col] for col in COLS_UMKM_4_MAIN}
    # Tie-breaking: sort descending by value; jika nilai identik → ascending by
    # nama sektor (abjad) agar hasil selalu reproducible persis, tidak bergantung
    # urutan implisit DataFrame. Kunci: (-nilai, nama_pendek) → Python sort stabil.
    ranked_4 = sorted(
        nilai_4.items(),
        key=lambda x: (-x[1], NAMA_SEKTOR_PENDEK[x[0]])
    )
    top1   = NAMA_SEKTOR_PENDEK[ranked_4[0][0]]
    top2   = NAMA_SEKTOR_PENDEK[ranked_4[1][0]]
    btm1   = NAMA_SEKTOR_PENDEK[ranked_4[-1][0]]  # terendah dari 4 utama
    btm2   = 'Lainnya'                             # selalu Lainnya
    sektor_top1_list.append(top1)
    sektor_top2_list.append(top2)
    sektor_bottom1_list.append(btm1)
    sektor_bottom2_list.append(btm2)
    # Simpan ranking lengkap 5 sektor (termasuk Lainnya) untuk JSON
    # Tie-breaking sama: (-nilai, nama_pendek) → alphabetical on tie
    nilai_5 = {col: row[col] for col in COLS_UMKM_5}
    ranked_5 = sorted(
        nilai_5.items(),
        key=lambda x: (-x[1], NAMA_SEKTOR_PENDEK[x[0]])
    )
    ranking_detail_list.append([
        {"rank": r+1,
         "sektor": NAMA_SEKTOR_PENDEK[s],
         "nilai": round(float(v), 1)}
        for r, (s, v) in enumerate(ranked_5)
    ])
# Tambahkan ke df_hasil
df_hasil['sektor_top1']    = sektor_top1_list
df_hasil['sektor_top2']    = sektor_top2_list
df_hasil['sektor_bottom1'] = sektor_bottom1_list
df_hasil['sektor_bottom2'] = sektor_bottom2_list
# Tampilkan tabel ranking per kecamatan
print(f"  {'Kecamatan':<17} {'Klaster':<9} {'Top-1':>10} {'Top-2':>10} "
      f"{'Bottom-1':>10} {'Bottom-2':>10} {'Flag'}")
print(f"  {'-'*80}")
for _, row in df_hasil.iterrows():
    flag = " ⚠️" if row['flag_imputasi'] == 'PERLU_VALIDASI' else ""
    print(f"  {row['nama_kecamatan']:<17} "
          f"K{row['label_cluster']}: {row['interpretasi'][:8]:<8} "
          f"{row['sektor_top1']:>10} {row['sektor_top2']:>10} "
          f"{row['sektor_bottom1']:>10} {row['sektor_bottom2']:>10}{flag}")
print(f"\n  Catatan: Bottom-2 selalu 'Lainnya' sesuai pola data BPS KBB.")
if KEG_IMPUTASI_TINGGI:
    print(f"  ⚠️  Kecamatan bertanda ⚠️ : ranking berbasis data imputasi, validasi kualitatif diperlukan.")
# Ringkasan: berapa kecamatan yang Top-1 di setiap sektor
print(f"\n  Ringkasan distribusi sektor sebagai Top-1 lintas kecamatan:")
for sektor in ['Makanan', 'Kerajinan', 'Fashion', 'Jasa']:
    n = (df_hasil['sektor_top1'] == sektor).sum()
    bar = '█' * n
    print(f"    {sektor:<12}: {n:>2} kecamatan  {bar}")
# Simpan ranking_detail ke list untuk ekspor JSON
df_hasil['ranking_sektor_json'] = ranking_detail_list

"""
# --- 5.5 Scatter Plot PCA 2D — disimpan sebagai scatter_cluster.png (path_grafik[2]) ---
# PERUBAHAN v2.0: Nama file diubah ke scatter_cluster.png sesuai spec §3.6"""

print("\n📌 [ASSESS 5.5] Membuat Scatter Plot PCA 2D → scatter_cluster.png...")
pca           = PCA(n_components=2, random_state=42)
X_pca         = pca.fit_transform(X_scaled)
explained_var = pca.explained_variance_ratio_
fig, ax = plt.subplots(figsize=(10, 7))
for cluster_id in range(K_OPTIMAL):
    mask  = labels == cluster_id
    label = f"Klaster {cluster_id}: {CLUSTER_KE_INTERPRETASI[cluster_id]}"
    ax.scatter(
        X_pca[mask, 0], X_pca[mask, 1],
        s=130, label=label,
        color=PALETTE[cluster_id % len(PALETTE)],
        edgecolors='white', linewidth=1.2, zorder=3, alpha=0.90
    )
    for i, row in df_hasil[mask].iterrows():
        ax.annotate(
            row['nama_kecamatan'],
            (X_pca[i, 0], X_pca[i, 1]),
            fontsize=7.5, ha='left',
            xytext=(5, 5), textcoords='offset points',
            color='#374151'
        )
# Plot centroid dalam ruang PCA
centroids_pca = pca.transform(kmeans_final.cluster_centers_)
ax.scatter(
    centroids_pca[:, 0], centroids_pca[:, 1],
    s=300, marker='*', color='black', zorder=5, label='Centroid', alpha=0.85
)
ax.set_xlabel(f'PC-1 ({explained_var[0]*100:.1f}% variansi)', fontsize=11)
ax.set_ylabel(f'PC-2 ({explained_var[1]*100:.1f}% variansi)', fontsize=11)
ax.set_title(
    f'Scatter Plot K-Means (K={K_OPTIMAL}) — Proyeksi PCA 2D\n'
    f'Total variansi terwakili: {sum(explained_var)*100:.1f}%',
    fontsize=12, fontweight='bold', pad=12
)
ax.legend(fontsize=9, framealpha=0.85, loc='best')
ax.grid(linestyle='--', alpha=0.35)
plt.tight_layout()
plt.savefig('scatter_cluster.png', bbox_inches='tight')
plt.show()
print("  ✅ Disimpan: scatter_cluster.png → path_grafik[2]")

"""# --- 5.6 BARU v2.0: Ekspor Output DB-Ready (3 File JSON) ---

"""

print("\n" + "="*70)
print("📌 [ASSESS 5.6] Ekspor Output DB-Ready (BARU v2.0)")
print("="*70)
print("   Tiga file JSON ini dirancang untuk langsung di-insert ke MariaDB")
print("   oleh Laravel Job setelah script selesai dijalankan.")
# ── Output A: metadata_output.json → INSERT ke tabel analisis ─────────────────
# Berisi: k_optimal, nilai metrik, scaler_params, path_grafik, dataset_snapshot
# Sesuai struktur tabel analisis §6.6
# Bangun dataset_snapshot sesuai format §4.5
snapshot_data = []
for _, row in df_processed.iterrows():
    kec_id = int(row['id_kecamatan'])
    fitur_db = {}
    for col_script in COLS_FITUR:
        col_db = KOLOM_MAP_SCRIPT_KE_DB[col_script]
        fitur_db[col_db] = round(float(row[col_script]), 4)
    snapshot_data.append({
        "id_kecamatan"   : kec_id,
        "tahun_demografi": TAHUN_DEMOGRAFI.get(kec_id),
        "fitur"          : fitur_db
    })
dataset_snapshot_json = {
    "tanggal_snapshot": TANGGAL_SNAPSHOT,
    "data"            : snapshot_data
}
metadata_output = {
    "k_optimal"        : int(K_OPTIMAL),
    "nilai_silhouette" : round(float(silhouette_final), 4),
    "nilai_dbi"        : round(float(dbi_final), 4),
    "scaler_params"    : scaler_params_dict,
    "model_params"     : {
        # Hyperparameter K-Means dan statistik konvergensi model final.
        # Disatukan dalam satu blok agar mudah di-log/audit oleh Laravel.
        "init"         : "k-means++",
        "n_init"        : 50,
        "max_iter"      : 500,
        "random_state"  : 42,
        "inertia_final" : round(float(kmeans_final.inertia_), 4),
        "n_iter"        : int(kmeans_final.n_iter_),
    },
    "path_grafik"      : ["elbow.png", "silhouette.png", "scatter_cluster.png"],
    "dataset_snapshot" : dataset_snapshot_json,
}
with open('metadata_output.json', 'w', encoding='utf-8') as f:
    json.dump(metadata_output, f, ensure_ascii=False, indent=2)
print("\n  ✅ Disimpan: metadata_output.json → INSERT ke tabel analisis")
# ── Output B: hasil_cluster_output.json → INSERT ke tabel hasil_cluster ───────
# PERUBAHAN v3.0: Tambah field sektor_top1, sektor_top2, sektor_bottom1,
# sektor_bottom2, dan ranking_sektor_5 (ranking lengkap per kecamatan).
# Ini adalah output utama Opsi A — per kecamatan, bukan per cluster centroid.
hasil_cluster_output = []
for idx, row in df_hasil.iterrows():
    hasil_cluster_output.append({
        "id_kecamatan"    : int(row['id_kecamatan']),
        "label_cluster"   : int(row['label_cluster']),
        "interpretasi"    : str(row['interpretasi']),     # profil klaster
        "sektor_top1"     : str(row['sektor_top1']),      # sektor tertinggi kecamatan
        "sektor_top2"     : str(row['sektor_top2']),      # sektor ke-2 tertinggi
        "sektor_bottom1"  : str(row['sektor_bottom1']),   # sektor terendah (dari 4 utama)
        "sektor_bottom2"  : "Lainnya",                    # selalu Lainnya
        "ranking_sektor_5": row['ranking_sektor_json'],   # [{rank, sektor, nilai}] lengkap
        "flag_imputasi"   : str(row['flag_imputasi']),
    })
with open('hasil_cluster_output.json', 'w', encoding='utf-8') as f:
    json.dump(hasil_cluster_output, f, ensure_ascii=False, indent=2)
print("  ✅ Disimpan: hasil_cluster_output.json → INSERT ke tabel hasil_cluster")
print(f"     Jumlah baris: {len(hasil_cluster_output)} (= {n_kecamatan} kecamatan)")
print(f"     Preview baris pertama:")
preview = {k: v for k, v in hasil_cluster_output[0].items() if k != 'ranking_sektor_5'}
print(f"       {preview}")
print(f"       ranking_sektor_5: {hasil_cluster_output[0]['ranking_sektor_5']}")
# ── Output C: centroid_output.json → INSERT ke tabel centroid ─────────────────
# Berisi: label_cluster, interpretasi sektor, profil dominan/rendah, nilai_fitur
# PERUBAHAN v3.0: skor_potensi digantikan oleh sektor_dominan, sektor_rendah,
# dan ranking_sektor (dari CLUSTER_KE_PROFIL_DETAIL) sesuai tujuan analisis.
centroid_output = []
for cluster_id in range(K_OPTIMAL):
    # Inverse transform ke skala PROPORSI (bukan absolut, karena scaler difit pada proporsi)
    # Hasilnya adalah nilai centroid dalam ruang proporsi [0,1] per sektor
    nilai_prop_centroid = scaler.inverse_transform(
        kmeans_final.cluster_centers_[cluster_id].reshape(1, -1)
    )[0]
    # Bangun nilai_fitur JSON dari COLS_FITUR_CLUSTER (proporsi + demografis)
    nilai_fitur_json = {}
    for i, col_cluster in enumerate(COLS_FITUR_CLUSTER):
        if col_cluster in COLS_PROP:
            # Proporsi sektor: simpan sebagai persen (x100 agar lebih readable)
            nama_json = 'f_prop_' + col_cluster.replace('PROP_', '').lower()
            nilai_fitur_json[nama_json] = round(float(nilai_prop_centroid[i]) * 100, 2)  # dalam %
        else:
            # Demografis: simpan apa adanya
            col_json = KOLOM_MAP_SCRIPT_KE_JSON.get(col_cluster, col_cluster.lower())
            nilai_fitur_json[col_json] = round(float(nilai_prop_centroid[i]), 4)
    profil = CLUSTER_KE_PROFIL_DETAIL[cluster_id]
    centroid_output.append({
        "label_cluster" : int(cluster_id),
        "interpretasi"  : CLUSTER_KE_INTERPRETASI[cluster_id],
        "sektor_dominan": profil["sektor_dominan"],    # ["Fashion", "Kerajinan"]
        "sektor_rendah" : profil["sektor_rendah"],     # ["Makanan"]
        "ranking_sektor": profil["ranking_sektor"],    # [{sektor, nilai, share_pct, vs_baseline}]
        "nilai_fitur"   : nilai_fitur_json,            # proporsi (%) + demografis
    })
with open('centroid_output.json', 'w', encoding='utf-8') as f:
    json.dump(centroid_output, f, ensure_ascii=False, indent=2)
print("  ✅ Disimpan: centroid_output.json → INSERT ke tabel centroid")
print(f"     Jumlah baris: {len(centroid_output)} (= {K_OPTIMAL} klaster)")
print(f"     Profil sektor per klaster:")
for item in centroid_output:
    print(f"       Klaster {item['label_cluster']}: {item['interpretasi']}")
    print(f"         → ranking_sektor: {[(s['sektor'], s['share_pct']) for s in item['ranking_sektor']]}")

"""# --- 5.7 Ekspor CSV Referensi Flat (Tetap ada untuk lampiran skripsi) ---

"""

print("\n📌 [ASSESS 5.7] Ekspor CSV flat (referensi lampiran skripsi)...")
OUTPUT_CSV = 'hasil_klasterisasi_umkm_kbb.csv'
# Kolom output CSV: identifier + nilai absolut UMKM + demografis +
#                   label cluster + interpretasi + ranking sektor per kecamatan
COLS_CSV = (
    COLS_IDENTIFIER
    + COLS_FITUR
    + ['label_cluster', 'interpretasi']
    + ['sektor_top1', 'sektor_top2', 'sektor_bottom1', 'sektor_bottom2']
    + ['flag_imputasi']
)
df_ekspor = df_hasil[COLS_CSV].copy()
df_ekspor.to_csv(OUTPUT_CSV, index=False, encoding='utf-8-sig')
print(f"  ✅ Disimpan: {OUTPUT_CSV}")
print(f"   Shape: {df_ekspor.shape} | Encoding: utf-8-sig")
print(f"   Kolom baru: sektor_top1, sektor_top2, sektor_bottom1, sektor_bottom2")
print(f"\n  Preview 5 baris pertama:")
print(df_ekspor[COLS_IDENTIFIER + ['label_cluster', 'sektor_top1', 'sektor_top2',
                                    'sektor_bottom1', 'sektor_bottom2']].head().to_string(index=False))

"""# ==============================================================================
# ## RINGKASAN AKHIR PIPELINE SEMMA v3.0
# ==============================================================================
"""

print(f"\n{'='*70}")
print("## RINGKASAN EKSEKUSI PIPELINE SEMMA v3.0")
print(f"{'='*70}")
print(f"""
  ┌──────────────────────────────────────────────────────────────────┐
  │  STAGE   │ Keterangan                                            │
  ├──────────────────────────────────────────────────────────────────┤
  │  SAMPLE  │ n={len(df_raw)} kecamatan, 8 fitur, 2 identifier (INT id)      │
  │  EXPLORE │ info(), head(), describe()+CV%, missing check, heatmap │
  │  MODIFY  │ Median imputation + StandardScaler (Z-score)          │
  │          │ → scaler_params diekspor (mean_ + scale_)             │
  │  MODEL   │ Elbow + Silhouette → K={K_OPTIMAL} optimal                    │
  │          │ K-Means (k-means++, n_init=50, random_state=42)       │
  │  ASSESS  │ Silhouette={silhouette_final:.4f} | DBI={dbi_final:.4f}                 │
  │          │ Interpretasi berbasis ranking skor_potensi centroid   │
  └──────────────────────────────────────────────────────────────────┘
  ── FILE OUTPUT ─────────────────────────────────────────────────────
  DB-Ready JSON (→ Laravel Job):
    metadata_output.json       → INSERT ke tabel analisis
    hasil_cluster_output.json  → INSERT ke tabel hasil_cluster
    centroid_output.json       → INSERT ke tabel centroid
  Grafik (→ path_grafik):
    elbow.png           [0]    → path_grafik[0]
    silhouette.png      [1]    → path_grafik[1]
    scatter_cluster.png [2]    → path_grafik[2]
  Lampiran Skripsi:
    explore_heatmap_korelasi.png   → Lampiran EDA
    model_centroid_heatmap.png     → Lampiran MODEL
    hasil_klasterisasi_umkm_kbb.csv → Lampiran ASSESS
  ✅ Pipeline SEMMA v2.0 selesai. Semua output siap untuk integrasi
     sistem Laravel + MariaDB WebGIS.
""")