<?php

namespace App\Jobs;

use App\Models\Analisis;
use App\Models\Centroid;
use App\Models\DatasetAgregat;
use App\Models\HasilCluster;
use App\Services\AggregationService;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Process;

class RunKMeansAnalysisJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public int $idAnalisis;

    /**
     * Create a new job instance.
     */
    public function __construct(int $idAnalisis)
    {
        $this->idAnalisis = $idAnalisis;
    }

    /**
     * Execute the job.
     */
    public function handle(AggregationService $aggregationService): void
    {
        $analisis = Analisis::find($this->idAnalisis);
        if (!$analisis) {
            return;
        }

        $analisis->update([
            'status_job' => 'diproses',
            'error_log' => null,
        ]);

        try {
            // 1. Generate snapshot JSON input
            $aggregationService->generateSnapshot();

            // 2. Locate Python executable & script
            $pythonBinary = $this->resolvePythonBinary();
            $scriptPath = $this->resolveScriptPath();

            // 3. Run Python process with system environment, PYTHONPATH, & PYTHONHASHSEED fix
            $userSite = getenv('APPDATA')
                ? getenv('APPDATA') . '\\Python\\Python310\\site-packages'
                : 'C:\\Users\\v14\\AppData\\Roaming\\Python\\Python310\\site-packages';

            $existingPyPath = getenv('PYTHONPATH') ?: '';
            $pythonPath = $userSite . ($existingPyPath ? ';' . $existingPyPath : '');

            $userProfile = getenv('USERPROFILE')
                ?: (getenv('HOMEDRIVE') && getenv('HOMEPATH') ? getenv('HOMEDRIVE') . getenv('HOMEPATH') : 'C:\\Users\\v14');

            $env = array_merge(
                $_SERVER,
                $_ENV,
                [
                    'PYTHONHASHSEED' => '0',
                    'PYTHONPATH' => $pythonPath,
                    'USERPROFILE' => $userProfile,
                    'HOMEDRIVE' => getenv('HOMEDRIVE') ?: 'C:',
                    'HOMEPATH' => getenv('HOMEPATH') ?: '\\Users\\v14',
                    'MPLCONFIGDIR' => sys_get_temp_dir() . '/matplotlib_config',
                    'SYSTEMROOT' => getenv('SystemRoot') ?: (getenv('SYSTEMROOT') ?: 'C:\\Windows'),
                    'WINDIR' => getenv('windir') ?: (getenv('WINDIR') ?: 'C:\\Windows'),
                    'PATH' => getenv('PATH') ?: (getenv('Path') ?: ''),
                    'TMP' => sys_get_temp_dir(),
                    'TEMP' => sys_get_temp_dir(),
                ]
            );

            $result = Process::path(base_path())
                ->env($env)
                ->run([$pythonBinary, $scriptPath]);

            if ($result->failed()) {
                $errorMessage = $result->errorOutput() ?: $result->output();
                $analisis->update([
                    'status_job' => 'gagal',
                    'error_log' => $errorMessage ?: 'Python process failed with exit code ' . $result->exitCode(),
                ]);

                return;
            }

            // 4. Read output JSON files
            $outputDir = storage_path('app/ml/output');
            $metadataFile = $outputDir . '/metadata_output.json';
            $hasilFile = $outputDir . '/hasil_cluster_output.json';
            $centroidFile = $outputDir . '/centroid_output.json';

            if (!File::exists($metadataFile) || !File::exists($hasilFile) || !File::exists($centroidFile)) {
                $analisis->update([
                    'status_job' => 'gagal',
                    'error_log' => 'One or more required JSON output files were not generated by Python ML Service.',
                ]);

                return;
            }

            $metadata = json_decode(File::get($metadataFile), true);
            $hasilClusterList = json_decode(File::get($hasilFile), true);
            $centroidList = json_decode(File::get($centroidFile), true);

            // 5. Copy graphic PNGs to public disk
            $publicAnalysisDir = storage_path('app/public/analysis');
            File::ensureDirectoryExists($publicAnalysisDir);

            $graphics = ['elbow.png', 'silhouette.png', 'scatter_cluster.png'];
            foreach ($graphics as $gfx) {
                $source = $outputDir . '/' . $gfx;
                if (File::exists($source)) {
                    File::copy($source, $publicAnalysisDir . '/' . $gfx);
                }
            }

            // 6. Database Transaction for atomic persistence
            DB::transaction(function () use ($analisis, $metadata, $hasilClusterList, $centroidList) {
                $analisis->update([
                    'k_optimal' => $metadata['k_optimal'] ?? null,
                    'nilai_silhouette' => $metadata['nilai_silhouette'] ?? null,
                    'nilai_dbi' => $metadata['nilai_dbi'] ?? null,
                    'dataset_snapshot' => $metadata['dataset_snapshot'] ?? null,
                    'scaler_params' => $metadata['scaler_params'] ?? null,
                    'path_grafik' => $metadata['path_grafik'] ?? ['elbow.png', 'silhouette.png', 'scatter_cluster.png'],
                    'model_params' => $metadata['model_params'] ?? null,
                    'status_job' => 'selesai',
                    'error_log' => null,
                ]);

                foreach ($hasilClusterList as $item) {
                    HasilCluster::create([
                        'id_analisis' => $analisis->id_analisis,
                        'id_kecamatan' => $item['id_kecamatan'],
                        'label_cluster' => $item['label_cluster'],
                        'interpretasi' => $item['interpretasi'] ?? null,
                        'sektor_top1' => $item['sektor_top1'] ?? null,
                        'sektor_top2' => $item['sektor_top2'] ?? null,
                        'sektor_bottom1' => $item['sektor_bottom1'] ?? null,
                        'sektor_bottom2' => $item['sektor_bottom2'] ?? 'Lainnya',
                        'ranking_sektor_5' => $item['ranking_sektor_5'] ?? null,
                        'flag_imputasi' => $item['flag_imputasi'] ?? 'OK',
                    ]);
                }

                foreach ($centroidList as $item) {
                    Centroid::create([
                        'id_analisis' => $analisis->id_analisis,
                        'label_cluster' => $item['label_cluster'],
                        'interpretasi' => $item['interpretasi'] ?? null,
                        'sektor_dominan' => $item['sektor_dominan'] ?? null,
                        'sektor_rendah' => $item['sektor_rendah'] ?? null,
                        'ranking_sektor' => $item['ranking_sektor'] ?? null,
                        'nilai_fitur' => $item['nilai_fitur'] ?? null,
                    ]);
                }

                DatasetAgregat::query()->update(['status_analisis' => 'sudah_dianalisis']);
            });
        } catch (\Throwable $e) {
            $analisis->update([
                'status_job' => 'gagal',
                'error_log' => $e->getMessage() . "\n" . $e->getTraceAsString(),
            ]);
        }
    }

    /**
     * Resolve path to Python binary.
     */
    protected function resolvePythonBinary(): string
    {
        if (env('PYTHON_PATH')) {
            return env('PYTHON_PATH');
        }

        $candidates = [
            base_path('ml-service/venv/Scripts/python.exe'),
            base_path('python/venv/Scripts/python.exe'),
            base_path('ml-service/venv/bin/python'),
            base_path('python/venv/bin/python'),
        ];

        foreach ($candidates as $bin) {
            if (File::exists($bin)) {
                return $bin;
            }
        }

        return 'python';
    }

    /**
     * Resolve path to Python script.
     */
    protected function resolveScriptPath(): string
    {
        $candidates = [
            base_path('ml-service/semma_kmeans_umkm_kbb.py'),
            base_path('python/SEMMA_KMeans_UMKM_KBB.py'),
            base_path('python/semma_kmeans_umkm_kbb.py'),
        ];

        foreach ($candidates as $script) {
            if (File::exists($script)) {
                return $script;
            }
        }

        return base_path('ml-service/semma_kmeans_umkm_kbb.py');
    }
}
